/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tela;

import javax.swing.JOptionPane;

/**
 *
 * @author eduardo
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpCadastros = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmCadastros = new javax.swing.JMenu();
        jmiTeste = new javax.swing.JMenuItem();
        jmiJogo = new javax.swing.JMenuItem();
        jmAjuda = new javax.swing.JMenu();
        jmiSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jdpCadastrosLayout = new javax.swing.GroupLayout(jdpCadastros);
        jdpCadastros.setLayout(jdpCadastrosLayout);
        jdpCadastrosLayout.setHorizontalGroup(
            jdpCadastrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 783, Short.MAX_VALUE)
        );
        jdpCadastrosLayout.setVerticalGroup(
            jdpCadastrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 532, Short.MAX_VALUE)
        );

        jmCadastros.setText("Cadastros");

        jmiTeste.setText("Teste");
        jmiTeste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiTesteActionPerformed(evt);
            }
        });
        jmCadastros.add(jmiTeste);

        jmiJogo.setText("Jogo");
        jmiJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiJogoActionPerformed(evt);
            }
        });
        jmCadastros.add(jmiJogo);

        jMenuBar1.add(jmCadastros);

        jmAjuda.setText("Ajuda");

        jmiSair.setText("Sair");
        jmiSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSairActionPerformed(evt);
            }
        });
        jmAjuda.add(jmiSair);

        jMenuBar1.add(jmAjuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpCadastros)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpCadastros)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSairActionPerformed
        JOptionPane.showMessageDialog(null, "\n ---- O programa está sendo encerrado! ---\n\n");
        System.exit(0);
        // fechando o programa quando o botão é apertado
    }//GEN-LAST:event_jmiSairActionPerformed

    private void jmiTesteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiTesteActionPerformed
        // criando novo objeto, da classe IfrEndereco
        IfrTeste ifrTeste = new IfrTeste();
        
        //adicionamos o objeto para dentro do Desktop Panel 
        jdpCadastros.add(ifrTeste);
        
        // depois informamos que o mesmo será visível
        ifrTeste.setVisible(true);
    }//GEN-LAST:event_jmiTesteActionPerformed

    private void jmiJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiJogoActionPerformed
        // criando novo objeto, da classe IfrEndereco
        IfrJogo ifrJogo = new IfrJogo();
        
        //adicionamos o objeto para dentro do Desktop Panel 
        jdpCadastros.add(ifrJogo);
        
        // depois informamos que o mesmo será visível
        ifrJogo.setVisible(true);
    }//GEN-LAST:event_jmiJogoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JDesktopPane jdpCadastros;
    private javax.swing.JMenu jmAjuda;
    private javax.swing.JMenu jmCadastros;
    private javax.swing.JMenuItem jmiJogo;
    private javax.swing.JMenuItem jmiSair;
    private javax.swing.JMenuItem jmiTeste;
    // End of variables declaration//GEN-END:variables
}
