
package tela;

/**
 *
 * @author eduardo
 */

import apoio.Formatacao;
import apoio.Validacao;
import dao.TesteDAO;
import entidade.Teste;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;

public class IfrTeste extends javax.swing.JInternalFrame {

    /**
     * Creates new form IfrTeste
     */
    
    int idTeste = 0;

    public IfrTeste() {
        initComponents();
        
        Formatacao.formatarCpf(tffCpf);
        Formatacao.formatarTelefone(tffTelefone);
        
        new TesteDAO().popularTabela(tblTeste, "");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnPesquisar = new javax.swing.JButton();
        tfdPesquisa = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTeste = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tffTelefone = new javax.swing.JFormattedTextField();
        tffCpf = new javax.swing.JFormattedTextField();
        tfdNome = new javax.swing.JTextField();
        tfdEmail = new javax.swing.JTextField();
        btnVoltar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        jLabel1.setText("Busca");

        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        tblTeste.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblTeste);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfdPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnPesquisar)
                    .addComponent(tfdPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Listagem", jPanel1);

        jLabel2.setText("Nome");

        jLabel3.setText("CPF");

        jLabel4.setText("Telefone");

        jLabel5.setText("Email");

        tffTelefone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tffTelefoneFocusLost(evt);
            }
        });
        tffTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tffTelefoneActionPerformed(evt);
            }
        });

        tffCpf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tffCpfFocusLost(evt);
            }
        });

        tfdEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfdEmailFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tffTelefone)
                    .addComponent(tffCpf)
                    .addComponent(tfdNome, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
                    .addComponent(tfdEmail))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfdNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tffCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tffTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(tfdEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Mantenção", jPanel2);

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        jButton6.setText("Consultar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVoltar)
                    .addComponent(btnSalvar)
                    .addComponent(btnEditar)
                    .addComponent(btnExcluir)
                    .addComponent(jButton6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void tffTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tffTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tffTelefoneActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        
        String nomeTeste = tfdNome.getText();
        String cpfTeste = Formatacao.removerFormatacao(tffCpf.getText());
        String email = tfdEmail.getText();
        String telefone = Formatacao.removerFormatacao(tffTelefone.getText());
        
        Teste teste = new Teste();
        // instanciando objeto da classe Fornecedor.java

        // definindo o endereco ao objeto específico colocado
        teste.setId(idTeste);
        teste.setNome(nomeTeste);
        teste.setCpf(cpfTeste);
        teste.setEmail(email);
        teste.setTelefone(telefone);

        TesteDAO testeDAO = new TesteDAO();

        // se o id for igual a 0, quer dizer que é uma inserção no bd, pois não tem id 0 no BD
        if (idTeste == 0) {
            // verificamos se o campo é nulo e caso for, salvamos o objeto endereco dentro do método
            // salvar do objeto enderecoDAO
            if (testeDAO.salvar(teste) == null) {
                // if == null significado que o retorno do método salvar foi null, conforme
                // o return null nesse método na class Endereco.java. Então, se retornou null é pq foi
                // possível inserir o objeto dentro do BD. Depois que a inserção foi feita, colcamos o campo sem texto
                // com setText abaixo e imprimos uma mensagem de sucesso ao usuário
                tfdNome.setText("");
                tfdEmail.setText("");
                tffCpf.setText("");
                tffTelefone.setText("");

                JOptionPane.showMessageDialog(this, "Registro salvo com sucesso!");
                tfdNome.requestFocus(); // coloca o foco(deixa o teclado dentro dele) para esse elemento
            } else { // se não retornou null o método de salvar conforme o if acima, é rodado esse erro para o usuário 
                JOptionPane.showMessageDialog(this, "Problemas ao salvar registro!");
            }
        } else { // se o idEndereco não for igual a 0, significa que temos uma edição
            // ou seja, foi pego o id de algum registro já existente no bd
            if (testeDAO.atualizar(teste) == null) {
                // if == null significado que o retorno do método salvar foi null, conforme
                // o return null nesse método na class Endereco.java. Então, se retornou null é pq foi
                // possível inserir o objeto dentro do BD. Depois que a inserção foi feita, colcamos o campo sem texto
                // com setText abaixo e imprimos uma mensagem de sucesso ao usuário
                tfdNome.setText("");
                tfdEmail.setText("");
                tffCpf.setText("");
                tffTelefone.setText("");

                JOptionPane.showMessageDialog(this, "Registro salvo com sucesso!");
                tfdNome.requestFocus(); // coloca o foco(deixa o teclado dentro dele) para esse elemento
            } else { // se não retornou null o método de salvar conforme o if acima, é rodado esse erro para o usuário 
                JOptionPane.showMessageDialog(this, "Problemas ao salvar registro!");
            }
        }
        idTeste = 0; // resetando o idEndereco para voltar ao valor original da variável
        new TesteDAO().popularTabela(tblTeste, ""); // popula a tabela novamente com os registros atuais, atualizando ela depois do salvamento
        jTabbedPane1.setSelectedIndex(0); // volta para a tela inicial
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        String idTabela = String.valueOf(tblTeste.getValueAt(tblTeste.getSelectedRow(), 0));
        idTeste = Integer.parseInt(idTabela); // método para transformar a string idTabela no int idFornecedor 

        //imprimindo no console o id selecionado para confirmar que o mesmo está ok durante a aplicaçaõ
        System.out.println(idTabela);

        // recebendo o retorno do método consultar id, passando o int idFornecedor como parametro 
        // e criando um novo objeto do tipo endereco para passar seu atributos
        Teste teste = new TesteDAO().consultarId(idTeste);

        // se for diferente de nulo, quer dizer que o objeto foi criado e preenchido
        if (teste != null) {
            jTabbedPane1.setSelectedIndex(1); // faz trocar para a aba de manutenção da aplicação ao invés da consulta
            tfdNome.setText(teste.getNome()); // define o texto do text field de manutenção como o mesmo presente no objeto endereco em que foi
            // encontrado o id passado como parametro
            tffCpf.setText(teste.getCpf());
            tfdEmail.setText(teste.getEmail());
            tffTelefone.setText(teste.getTelefone());
            

            tfdNome.requestFocus(); // deixa o mouse em cima desse text field
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao editar Teste: ");
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        String idTabela = String.valueOf(tblTeste.getValueAt(tblTeste.getSelectedRow(), 0));
        idTeste = Integer.parseInt(idTabela); // método para transformar a string idTabela no int idFornecedor 

        //imprimindo no console o id selecionado para confirmar que o mesmo está ok durante a aplicaçaõ
        System.out.println(idTeste);

        // recebendo o retorno do método consultar id, passando o int idEndereco como parametro 
        // e criando um novo objeto do tipo endereco para passar seu atributos

        // testando para verificar se é nulo ou não
        // se for nulo, quer dizer que está ok conforme o método excluir na classe EnderecoDAO e 
        // será feita a exlusão
        if (new TesteDAO().excluir(idTeste) == null) {          
            JOptionPane.showMessageDialog(this, "Exclusão feita com sucesso!");
            
            new TesteDAO().popularTabela(tblTeste, ""); // gera novamente a table depois da exlusão
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao excluir ENDERECO!");
        }        
        idTeste = 0; // reseta o valor da variável para que não tenhamos problemas na inserção de novos registros após a exlusão de outros
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        new TesteDAO().popularTabela(tblTeste, tfdPesquisa.getText());
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       
        ArrayList<Teste> testes = new ArrayList();
        
        testes = new TesteDAO().consultarTodos();
        
        for(int i = 0; i < testes.size(); i++) {
        
            System.out.println("Id: " + testes.get(i).getId());
            System.out.println("Nome: " + testes.get(i).getNome());
            System.out.println("CPF: " + testes.get(i).getCpf());
            System.out.println("E-mail: " + testes.get(i).getEmail());
            System.out.println("Telefone: " + testes.get(i).getTelefone());
        
            System.out.println("");
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void tffCpfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tffCpfFocusLost
        if(!Validacao.validarCPF(tffCpf.getText())) {
            tffCpf.setBackground(Color.red);
        } else {
            tffCpf.setBackground(Color.white);
        }
    }//GEN-LAST:event_tffCpfFocusLost

    private void tffTelefoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tffTelefoneFocusLost
        if(!Validacao.validarTelefone(tffTelefone)) {
            tffTelefone.setBackground(Color.red);
        } else {
            tffTelefone.setBackground(Color.white);
        }
    }//GEN-LAST:event_tffTelefoneFocusLost

    private void tfdEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfdEmailFocusLost
       if(!Validacao.validarEmail(tfdEmail)) {
            tfdEmail.setBackground(Color.red);
        } else {
            tfdEmail.setBackground(Color.white);
        }
    }//GEN-LAST:event_tfdEmailFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblTeste;
    private javax.swing.JTextField tfdEmail;
    private javax.swing.JTextField tfdNome;
    private javax.swing.JTextField tfdPesquisa;
    private javax.swing.JFormattedTextField tffCpf;
    private javax.swing.JFormattedTextField tffTelefone;
    // End of variables declaration//GEN-END:variables
}
